name: Vault Sync

on:
  workflow_dispatch: # Allows manual or API-triggered runs
  push:
    branches:
      - main # Or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Vault
        uses: actions/checkout@v4

      - name: Configure Git User
        run: |
          git config user.name "NoteBot"
          git config user.email "notebot@example.com"

      - name: Clean Ignored Files
        run: |
          rm -f ./.obsidian/workspace.json
          rm -f ./.obsidian/workspaces.json
          find . -type f -name '*.json' -delete

      - name: Commit and Push Changes (if any)
        run: |
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "chore: Remote sync $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit from remote."
          fi