name: Nightly Vault Sync

on:
  schedule:
    - cron: '59 23 * * *' # Runs daily at 11:59 PM UTC
  workflow_dispatch: # Allows manual runs from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Vault
        uses: actions/checkout@v4
        with:
          # Fetch all history for accurate change detection
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config user.name "NoteBot"
          git config user.email "notebot@example.com"

      - name: Clean Ignored Files
        run: |
          # Remove active workspace state and other volatile JSON files
          rm -f ./.obsidian/workspace.json
          rm -f ./.obsidian/workspaces.json
          # Remove other json files as requested
          find . -type f -name '*.json' -delete
          echo "Cleaned up ignored and volatile files."

      - name: Commit and Push Changes
        run: |
          git add .
          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            echo "Changes detected. Committing and pushing..."
            git commit -m "chore: Nightly sync $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes detected. Nothing to commit."
          fi
